### ISSUE TITLE
Would it be possible to get some sample output?

### ISSUE THREAD

**Issue by e1ven** [chick-fil-a/bovine#2]
I know it's super early, but the tool looks awesome.
I'd love to see some screenshots or output, so I can get a sense of how this could be best used, before committing to the installation.

Thanks for releasing it publicly!

**Comment by nocow4bob** [comment]
Absolutely! I had been meaning to put a quick userguide together with some screenshots to help explain what this is all about. You can check it out here - [https://github.com/chick-fil-a/bovine/blob/master/docs/userguide.md](url)

Let me know if you have any questions!
